import Head from "next/head";
import Image from "next/image";
import * as go from "gojs";
import { ReactDiagram } from "gojs-react";
import { useEffect, useState } from "react";
import { initDiagram } from "@services/diagram";
import { useSession } from "next-auth/react";
import { useAppInsightsContext } from "@microsoft/applicationinsights-react-js";

const handleModelChange = (changes: go.IncrementalData) => {
  console.log(changes);
};

export default function Home() {
  const appInsights = useAppInsightsContext();
  const [sent, setSent] = useState(false);
  const { data, status } = useSession();
    useEffect(() => {
      const user = {
        name: data?.user?.name || "",
        email: data?.user?.email || "",
        expires: data?.expires || "",
        status: status,
        host: window ? window.location.hostname : "unknown",
      };
      
      if (
        user.status === "authenticated" &&
        !user.host.toLowerCase().includes("localhost") &&
        !sent
      ) {
        console.log(user);
        appInsights.trackEvent({ name: "User", properties: user });
        setSent(true);
      }
    }, [data, status, appInsights, sent]);
  return (
    <>
      <Head>
        <title>Serverless AzureML Components</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main>
        <ReactDiagram
          initDiagram={initDiagram}
          divClassName="diagram-component"
          style={{ height: "100vh", width: "100vw" }}
          nodeDataArray={[
            {
              key: 0,
              title: "Cognitive Services Query",
              text: "Fetch data from Azure Cognitive Services",
              image: "/icons/Search-Services.svg",
              loc: "0 0",
              category: "transform",
            },
            {
              key: 1,
              title: "SQL Server Query",
              text: "Fetch data from SQL Server",
              image: "/icons/SQL-Database.svg",
              loc: "400 0",
              category: "transform",
            },
            {
              key: 2,
              title: "Text Analytics Query",
              text: "Run Text Analytics",
              image: "/icons/Cognitive-Services.svg",
              loc: "400 0",
              category: "transform",
            },
            {
              key: 3,
              title: "Custom Script Processor",
              text: "Run Script",
              image: "/icons/Code.svg",
              loc: "400 0",
              category: "transform",
            },
            {
              key: 4,
              title: "Azure Functions",
              text: "Process using Azure Functions",
              image: "/icons/Function-Apps.svg",
              loc: "800 800",
              category: "transform",
            },
            {
              key: 5,
              text: "input1",
              loc: "800 800",
              category: "input",
            },
            {
              key: 6,
              text: "input2",
              loc: "800 800",
              category: "input",
            },
          ]}
          linkDataArray={[
            { key: -1, from: 0, to: 1 },
            { key: -2, from: 0, to: 2 },
            { key: -3, from: 1, to: 1 },
            { key: -4, from: 2, to: 3 },
            { key: -5, from: 3, to: 0 },
          ]}
          onModelChange={handleModelChange}
        />
      </main>
    </>
  );
}
